name: Sync Data

on:
  schedule:
    - cron: "30 18 * * *" # At 10:30 on every day-of-week from Monday through Friday
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL:
        ${{ secrets.DATABASE_URL }}

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: start
